# Programski jezik Python
## Kratek pregled

Delovni zvezek "Jupyter" je brezplačno, odprtokodno, interaktivno spletno orodje. Gre za računalniški zvezek, ki je postal široko uporabljen po vsem svetu. Njegova prednost je v kombinaciji dveh tipov celic:
* Markdown ([Cheat sheet](https://www.markdownguide.org/cheat-sheet/))
* Code

Raziskovalci ga uporabljajo za kombiniranje programske kode, izpisov med izvajanjem kode, eksplikativnega besedila in vključevanja večpredstavnostnih virov, vse v enem dokumentu.
Trenutna celica je torej tipa Markdown in služi za opis dela.

## Vzpostavitev virtualnega okolja

bash:
python -m venv okolje
source okolje/bin/activate

## Namestitev knjižnic
bash:
pip install ime-knjiznice

# Osnove

Sintaksa kode v datotekah .py in .ipynb, čeprav gre v obeh primerih za programski jezik Python, ni popolnoma enaka.
Primer tega je naslednja celica:

In [1]:
"Neprikazan izpis"
"Prikazan izpis"

'Prikazan izpis'

Vidimo, da se izpiše le zadnji. Zatorej se bomo raje osredotočili na podobnosti. Za izpis v konzolo bomo raje uporabljali način print("izpis"). print() samodejno doda novo vrstico.

In [2]:
# Izpis v konzolo
print("Hello world")

besedilo = "Hello world"
print(besedilo)

# \n nova vrstica
print("Hello \nworld")

# Brez nove vrstice
print("Hello ", end='')
print("world")

Hello world
Hello world
Hello 
world
Hello world


Glavne pretvorbe med tipi:
* int() - cela števila
* float() - realna števila (npr. 2.6, 3.7)
* str() - niz
* bool() - logična vrednost: True, False

In [3]:
# Spremenljivka x, tipa int, vrednost 1
# prirejanje vrednosti
x = 1
print(x)

x1 = 1.1
print(x1)

y1 = int(x1)
print(y1)

y2 = float(x)
print(y2)

x2 = 55.545003421
print(x2)

y3 = round(x2, 3)
print(y3)

1
1.1
1
1.0
55.545003421
55.545


Python torej v osnovi avtomatsko določi tip spremenljivke, ki jih lahko dodatno pretvarjamo. Velikokrat nam je lahko v pomoč tudi naslednje:

In [4]:
print(type(besedilo))

print(type(x))

print(type(y2))

<class 'str'>
<class 'int'>
<class 'float'>


## Nekaj osnovnih ukazov

In [5]:
x = 1
print("x=" + str(1))

# vsota
y = x + 1
print(y)

# odštevanje
y = y - 1
print(y)

x = 2
# potenciranje
x = x**2
print(x)

# modulus - ostanek pri deljenju
x = x % 3
print(x)

# deljenje
x = 10
x = x / 2
print(x)
print("Pretvorba nazaj v int: " + str(int(x)))

x=1
2
1
4
1
5.0
Pretvorba nazaj v int: 5


# Seznami

In [6]:
# Ustvarimo prazen seznam (angl. list, podobno kot polje (angl. array), vendar lahko shrani različne tipe spremenljivk)
prazen_seznam = []
# Ustvarimo prazen seznam, v katerega bomo vstavili 10 spremenljivk tipa int
prazen_seznam2 = [int] * 10

print(prazen_seznam)
print(prazen_seznam2)

seznam = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Izpis prvega elementa
print("\n" + seznam[0])
# Izpis zadnjega elementa
print(seznam[-1])

# Izpis elementov pred indeksom 3
print(seznam[:3])
# Izpis elementov po indeksu 1
print(seznam[1:])
# Izpis elementa z indeksom 1 in 2 (vključno prvi, do drugi)
print(seznam[1:3])

print("\n")
# Izpis celotnega seznama
print(seznam[:])

for elem in seznam:
    print(elem)

# Izpis v eni vrstici, brez ['','']
print(*seznam)

# Dodajanje elementa na konec seznama
seznam.append('y')

print("\n" + str(seznam))
# vrni indeks elementa (če je več enakih, vrne prvega)
print(seznam.index('y'))

# vrni število elementov 'y'
print(seznam.count('y'))

[]
[<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]

a
j
['a', 'b', 'c']
['b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
['b', 'c']


['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
a
b
c
d
e
f
g
h
i
j
a b c d e f g h i j

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'y']
10
1


# Slovarji
* angl. dictionary
* ključ:vrednost - key:value

In [7]:
slovar = {
    "artikel": "sliva",
    "poreklo": "Slovenija",
    "kolicina": 50
}

# Izpis vrednosti za poreklo
print(slovar['poreklo'])
print(slovar.get('poreklo'))

# Kaj se zgodi, če vrednost ni prisotna?
# print (slovar['ne-obstaja']) --> KeyError: 'ne-obstaja'
# Zato je priporočena uporaba .get metode -- vrne None
print(slovar.get('ne-obstaja'))

# Izpis dolžine slovarja
print(len(slovar))

print()
# Izpis ključev
print(slovar.keys())
# Izpis vrednosti
print(slovar.values())
# Izpis elementov
print(slovar.items())

Slovenija
Slovenija
None
3

dict_keys(['artikel', 'poreklo', 'kolicina'])
dict_values(['sliva', 'Slovenija', 50])
dict_items([('artikel', 'sliva'), ('poreklo', 'Slovenija'), ('kolicina', 50)])


# If elif else

In [8]:
x = 5
y = 10

if x > y:
    print("x je vecji od y")
elif x == y:
    print("x je enak y")
else:
    print("y je vecji od x")

y je vecji od x


# for zanka

In [9]:
stevila = [10, 20, 30, 40]

# Izpis vsakega števila
for stevilo in stevila:
    print(stevilo)

print()
# Izpis vsakega indeksa števila
for i in range(len(stevila)):
    print(i)

print()
# Izpis indeksa in števila
for index, vrednost in enumerate(stevila):
    print(index, vrednost)

10
20
30
40

0
1
2
3

0 10
1 20
2 30
3 40


# While zanka
While zanka - izvajanje dokler ... ne dosežemo pogoja

### While - continue

In [10]:
i = 0
# Dokler je i manjši od 6 - se ponavlja
while i < 6:
    i += 1
# Pogoj - če je i enak 3, nadaljuj izvajanje
    if i == 3:
        print("Ta del je preskočen")
        continue
    print(i)

1
2
Ta del je preskočen
4
5
6


### while - break
While zanka - izvajanje dokler ne dosežemo pogoja

In [11]:
i = 1
# Dokler je i manjši od 6 - se ponavlja
while i < 6:
    print(i)
    # če je i enak 3, prekini
    if i == 3:
        print('Zanka končana.')
        break
    i += 1

1
2
3
Zanka končana.


### While - else

In [12]:
i = 1
while i < 6:
    print(i)
    i += 1
else:
    print("i is no longer less than 6")

1
2
3
4
5
i is no longer less than 6


# NumPy
NumPy je temeljna knjižica za delo z matrikami v Pythonu. Omogoča delo z matrikami poljubnih dimenzij. Ponuja mnogo različnih operacij nad njimi, npr., matematične, logične, manipulacije oblike, transformacije, algebrske operacije, razvrščanje elementov ipd. Je ena izmed najbolj poznanih knjižnic za programski jezik Python in se lahko pohvali z izredno hitrostjo izvajanja operacij, primerljivo programskemu jeziku C, s preprostostjo programskega jezika Python.

In [13]:
import numpy as np

# Ustvari polje števil
polje_stevil = np.array([1, 2, 3])
# Pripni dodatna števila
polje_stevil = np.append(polje_stevil, [4, 5, 6])
# Izpis polja
print(polje_stevil)

[1 2 3 4 5 6]


In [14]:
# P olje poljubnih dimenzij
prvo_polje_stevil = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
drugo_polje_stevil = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(drugo_polje_stevil)

drugo_polje_stevil = drugo_polje_stevil.reshape(-1)
print()
print(drugo_polje_stevil)

# Seveda so možne tudi bistveno kompleksnejše operacije, npr.
# Vsota kvadratov števil absolutnih vrednosti dveh polij
drugo_polje_stevil = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.sum(np.square(np.abs(prvo_polje_stevil-drugo_polje_stevil)))

# Deljenje vseh elementov np.array s številom 3
drugo_polje_stevil = np.divide(drugo_polje_stevil, 3)
print()
print(drugo_polje_stevil)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]

[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


# Delo s csv

In [15]:
import csv

with open('../podatkovne-zbirke/sport-manjkajoci.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['duration', 'distance', 'average_hr', 'average_altitude', 'max_altitude', 'calories', 'ascent', 'descent']
['54.0', '8.869410156', '117', '418.3103138', '483.2000122', '374', '245.8000183', '208.2000122']
['54.43333333', '14.19421973', '122', '477.5547162', '529.4000244', '316', '122.0002441', '86.40023804']
['67.63333333', '24.59965039', '149', '98.83924418', '223.1999969', '499', '357.7999897', '349.3999901']
['74.13333333', '17.48390039', '', '125.3543787', '175.6000061', '263', '107.0', '112.7999954']
['52.38333333', '17.53968945', '118', '742.4507795', '800.7999878', '374', '328.3999023', '329.999939']
['74.73333333', '18.76351953', '', '262.2846688', '368.3999939', '380', '270.2002869', '320.6002808']
['68.65', '10.3579502', '100', '699.8537351', '758.7999878', '179', '237.8000488', '237.8000488']
['77.2', '30.64191016', '128', '84.54064255', '105.8000031', '625', '121.4000015', '120.4000015']
['54.98333333', '16.64184961', '128', '448.9744195', '783.2000122', '363', '376.199890